name: Test Azure Connection

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
    - name: Test Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Test ACR Access
      run: |
        echo "ACR Server: ${{ secrets.ACR_LOGIN_SERVER }}"
        echo "✅ Secrets are configured!"
        az acr show --name $(echo "${{ secrets.ACR_LOGIN_SERVER }}" | cut -d'.' -f1)
